//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub mod prelude;

pub mod article;
pub mod category;
pub mod comment;
pub mod forum;
pub mod menu;
pub mod r_article_tag;
pub mod r_role_menu;
pub mod r_role_rersource;
pub mod r_user_role_forum;
pub mod resource;
pub mod role;
pub mod tag;
pub mod user;
