//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "resource")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub method: String,
    pub href: String,
    pub desc: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::r_role_rersource::Entity")]
    RRoleRersource,
}

impl Related<super::r_role_rersource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RRoleRersource.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::r_role_rersource::Relation::Role.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::r_role_rersource::Relation::Resource.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
