//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub desc: String,
    pub parent_id: Option<Uuid>,
    pub updated_at: DateTime,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::r_role_menu::Entity")]
    RRoleMenu,
    #[sea_orm(has_many = "super::r_role_rersource::Entity")]
    RRoleRersource,
    #[sea_orm(has_many = "super::r_user_role::Entity")]
    RUserRole,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
}

impl Related<super::r_role_menu::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RRoleMenu.def()
    }
}

impl Related<super::r_role_rersource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RRoleRersource.def()
    }
}

impl Related<super::r_user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RUserRole.def()
    }
}

impl Related<super::menu::Entity> for Entity {
    fn to() -> RelationDef {
        super::r_role_menu::Relation::Menu.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::r_role_menu::Relation::Role.def().rev())
    }
}

impl Related<super::resource::Entity> for Entity {
    fn to() -> RelationDef {
        super::r_role_rersource::Relation::Resource.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::r_role_rersource::Relation::Role.def().rev())
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::r_user_role::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::r_user_role::Relation::Role.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
